buildscript {
    repositories {
        maven { url = 'https://maven.minecraftforge.net' }
        mavenCentral()
        maven {
            name = "sonatype"
            url = "https://oss.sonatype.org/content/repositories/snapshots/"
        }
        maven {
            url "https://plugins.gradle.org/m2/"
        }
        maven {
            url "https://repo.spongepowered.org/repository/maven-public/"
            content { includeGroup "org.spongepowered" }
        }
    }
    dependencies {
        classpath group: 'net.minecraftforge.gradle', name: 'ForgeGradle', version: '5.1.+', changing: true
		classpath group: 'io.github.0ffz', name: 'gpr-for-gradle', version: '1.+', changing: true
    }
}

apply plugin: 'io.github.0ffz.github-packages'
apply plugin: 'net.minecraftforge.gradle'

version = mod_version
group = 'mrthomas20121.functional_aether'
archivesBaseName = "Functional Aether ${minecraft_version}"

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

minecraft {
    mappings channel: 'official', version: minecraft_version

    runs {
        client {
            workingDirectory project.file('run')

            property 'forge.logging.markers', 'REGISTRIES'

            property 'forge.logging.console.level', 'debug'

            property 'mixin.env.remapRefMap', 'true'
            property 'mixin.env.refMapRemappingFile', "${projectDir}/build/createSrgToMcp/output.srg"

            mods {
                functional_aether {
                    source sourceSets.main
                }
            }
        }

        server {
            workingDirectory project.file('run')

            property 'forge.logging.markers', 'REGISTRIES'

            property 'forge.logging.console.level', 'debug'

            property 'mixin.env.remapRefMap', 'true'
            property 'mixin.env.refMapRemappingFile', "${projectDir}/build/createSrgToMcp/output.srg"

            mods {
                functional_aether {
                    source sourceSets.main
                }
            }
        }

        data {
            workingDirectory project.file('run')

            property 'forge.logging.markers', 'REGISTRIES'

            property 'forge.logging.console.level', 'debug'

            property 'mixin.env.remapRefMap', 'true'
            property 'mixin.env.refMapRemappingFile', "${projectDir}/build/createSrgToMcp/output.srg"

            args '--mod', 'functional_aether', '--all', '--output', file('src/generated/resources/'), '--existing', file('src/main/resources/'), '--existing-mod', 'functionalstorage'

            mods {
                functional_aether {
                    source sourceSets.main
                }
            }
        }
    }
}

// Include resources generated by data generators.
sourceSets.main.resources { srcDir 'src/generated/resources' }

repositories {
    maven githubPackage.invoke("The-Aether-Team/The-Aether")
    maven githubPackage.invoke("The-Aether-Team/Nitrogen")
    maven githubPackage.invoke("The-Aether-Team/Cumulus")
    maven {
        name 'cursemaven'
        url "https://cursemaven.com"
    }
    maven {
        name "Curio"
        url "https://maven.theillusivec4.top/"
    }
    maven {
        name 'crafttweaker'
        url 'https://maven.blamejared.com'
    }
    maven { // JEI
        name 'Prog Maven'
        url 'https://dvs1.progwml6.com/files/maven'
    }
}

dependencies {
    minecraft "net.minecraftforge:forge:${minecraft_version}-${forge_version}"

	compileOnly(fg.deobf("mezz.jei:jei-${minecraft_version}-forge-api:${jei_version}"))
    compileOnly(fg.deobf("mezz.jei:jei-${minecraft_version}-common-api:${jei_version}"))
    runtimeOnly(fg.deobf("mezz.jei:jei-${minecraft_version}-forge:${jei_version}"))
	
	// aether and deps
	compileOnly "com.aetherteam.aether:aether:${minecraft_version}-${aether_version}"
    runtimeOnly fg.deobf("com.aetherteam.aether:aether:${minecraft_version}-${aether_version}")
	
	implementation fg.deobf("com.aetherteam.nitrogen:nitrogen_internals:${nitrogen_version}")
    implementation fg.deobf("com.aetherteam.cumulus:cumulus_menus:${cumulus_version}")

    implementation fg.deobf('com.github.glitchfiend:TerraBlender-forge:1.20.1-3.0.1.7')
    implementation fg.deobf("curse.maven:aeroblender-879879:4789008")

    // aether gravitation
    implementation fg.deobf("curse.maven:aether-gravitation-855631:6123604")
    // deep aether
    implementation fg.deobf("curse.maven:deep-aether-852465:5441091")
    // aether redux
    implementation fg.deobf("curse.maven:aether-redux-867237:5872671")
    // gecko lib
    implementation fg.deobf("curse.maven:geckolib-388172:6027567")

    // curio
    runtimeOnly fg.deobf("top.theillusivec4.curios:curios-forge:${curio_version}")
    compileOnly fg.deobf("top.theillusivec4.curios:curios-forge:${curio_version}:api")
	
	implementation fg.deobf("curse.maven:functional-storage-556861:${functional_storage_version}")
    implementation fg.deobf("curse.maven:titanium-287342:${titanium_version}")
}

jar {
    manifest {
        attributes([
            "Specification-Title": "FunctionalTFC",
            "Specification-Vendor": "Mrthomas20121",
            "Specification-Version": "1",
            "Implementation-Title": project.name,
            "Implementation-Version": project.version,
            "Implementation-Vendor" :"functional_aether",
            "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }
}

jar.finalizedBy('reobfJar')